#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
osascript -e 'tell app "System events" to display dialog "Your SSH Public Key has been copied to your keyboard. Paste it into your Github account: https://github.com/settings/ssh" buttons {"OK"}'
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Please download & install wkHtml2PDF to generate even better PDFs out of HTML & CSS ..."
  open http://code.google.com/p/wkhtmltopdf/downloads/list

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Installing Wget, because you'll need it ..."
  brew install wget

echo "Installing HTMLdoc, to generate PDF out of HTML ..."
  brew install htmldoc

echo "Installing RAR, because you'll need it..."
  brew install unrar

echo "Installing Git, a fast version control system ..."
  brew install git

echo "Installing MongoDB, a scalable, high-performance, document-oriented database ..."
  brew install mongodb

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install -f imagemagick --disable-openmp

echo "Installing ZSH ..."
  wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source \"/Users/`whoami`/.rvm/scripts/rvm\"" >> ~/.zshrc
  source "/Users/`whoami`/.rvm/scripts/rvm"

bash < <(curl -s https://raw.github.com/railsland/laptop/master/ruby)
